# Generated by Django 5.1 on 2025-01-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASHBOARD', '0002_alter_employee_base_salary_alter_folder_ifc_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='activity_sector',
            field=models.CharField(choices=[('IND-FAB', 'Industrie et Fabrication'), ('TECH-INNOV', 'Technologies et Innovation'), ('SANTE-BE', 'Santé et Bien-être'), ('CREA-CUL', 'Creation et Culture'), ('ENV-AGR', 'Environnement et Agriculture'), ('COM-DIST', 'Commerce et Distribution'), ('TOUR-HOT', 'Tourisme et Hôtellerie'), ('EDUC-FORM', 'Education et Formation'), ('FIN', 'Finances')], max_length=15),
        ),
    ]
