# Generated by Django 5.1 on 2025-01-05 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASHBOARD', '0003_alter_convention_activity_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DASHBOARD.employee'),
        ),
    ]
