# Generated by Django 5.1 on 2025-01-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DASHBOARD', '0004_alter_folder_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='convention',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='company',
        ),
    ]
