# Generated by Django 5.1 on 2025-01-06 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASHBOARD', '0005_remove_employee_convention_remove_folder_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='activity_sector',
            field=models.CharField(blank=True, choices=[('IND-FAB', 'Industrie et Fabrication'), ('TECH-INNOV', 'Technologies et Innovation'), ('SANTE-BE', 'Santé et Bien-être'), ('CREA-CUL', 'Creation et Culture'), ('ENV-AGR', 'Environnement et Agriculture'), ('COM-DIST', 'Commerce et Distribution'), ('TOUR-HOT', 'Tourisme et Hôtellerie'), ('EDUC-FORM', 'Education et Formation'), ('FIN', 'Finances')], max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='settingconvention',
            name='convention',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DASHBOARD.convention'),
        ),
    ]
