# Generated by Django 5.1 on 2025-01-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASHBOARD', '0006_alter_convention_activity_sector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convention',
            name='activity_sector',
        ),
        migrations.AlterField(
            model_name='company',
            name='activity_sector',
            field=models.CharField(choices=[('IND-FAB', 'Industrie et Fabrication'), ('TECH-INNOV', 'Technologies et Innovation'), ('SANTE-BE', 'Santé et Bien-être'), ('CREA-CUL', 'Creation et Culture'), ('FIN', 'Finances'), ('ENV-AGR', 'Environnement et Agriculture'), ('COM-DIST', 'Commerce et Distribution'), ('TOUR-HOT', 'Tourisme et Hôtellerie'), ('EDUC-FORM', 'Education et Formation'), ('AUT', 'Autre')], max_length=15),
        ),
        migrations.AlterField(
            model_name='convention',
            name='name',
            field=models.CharField(choices=[('C-SEC_COM', 'Convention du secteur commercial'), ('C-SEC_MIN', 'Convention du secteur minier'), ('C-SEC_PET', 'Convention du secteur pretrolier'), ('C-SEC_SAN', 'Convention du secteur sanitaire'), ('C-SEC_AGR', 'Convention du secteur agricole'), ('C-SEC_EDU', 'Convention du secteur éducatif'), ('C-SEC_TEC', 'Convention du secteur technologique'), ('C-SEC_TOU', 'Convention du secteur touristique'), ('C-IAS19', 'Convention selon la norme IAS 19'), ('C-AUTRE', 'Autre convention')], max_length=150, unique=True),
        ),
    ]
